---
session: 071
title: Perspective P4 Cross-Family Reviewer Laundering-Audit — hybrid adoption, with evidence limits preserved
date: 2026-04-26
status: complete
perspective: cross-family-reviewer-laundering-audit
committed_at: 2026-04-26T16:19:34+10:00
---

## Q1 — Shift to harness-side measurement, but do not collapse all surfaces into one enforcement jump

The design-space §4.1 unifies EF-067, EF-059, and EF-068 as spec-side encouragement without harness-side measurement. That frame is valid. `validation-approach.md` v7 §Principled Asymmetry says routine checks may remain self-assessed, but “claims about unresolved validation debt, substantive progress, engine-definition change, and repeated warnings require stateful or distinct review.” The three records are all adjacent to that class.

The audit qualification is scope: the evidence supports adding harness-side measurement for load-bearing cross-session-state claims, not making every operational preference a hard precondition immediately. EF-068’s substrate non-use chain in design-space §3.1 is strong evidence that “organic-use opportunity” framing decays to non-use. It is weaker evidence for immediate full (z6) hard-dependency. EF-067’s chain in design-space §3.2 is strong evidence that reviewer cost self-report is not ground truth. EF-059’s triage says the digest arc is activated, but activation is not the same as proving the largest schema must ship in one bundle.

## Q2 — Minimum viable first, full root-cause arc second

The laundering-audit position favors the design-space §6 candidate (ε), with the first phase closer to (β) than (α). The S062 §10.4-M16 minimum-viable-response precedent matters because the design-space’s strongest evidence supports immediate bounded correction: load MCP retrieval by default, require `forward_references('S<NNN>')`, and add a WARN-only evidence probe. It does not yet justify bundling all EF-067/059/068 surfaces into one full harness implementation as the next direct move.

The n=5 substrate chain validates “spec-side encouragement under ordinary salience is insufficient.” It does not validate that a full digest implementation is the smallest reliable next step. The S071 session-open substrate exercise, if caused by the design-space being salient, is a warning that behavior changes under audit attention may not be durable. That argues for observation after (β), not for no action.

## Q3 — Load by default is justified; deferred-tool friction is not worth preserving here

Design-space §7 Q3 estimates the three substrate schemas at roughly 1000 tokens, trivial against the session-open context budget. EF-068’s intake identifies the deferred-tool step as small but meaningful at the habit-forming moment. The audit view is that preserving discoverability friction is not load-bearing enough to justify continued n→0 use.

Load by default should not be framed as full harness enforcement. It is a friction correction. Tool availability should still be visible in the session-open record, but the engine should stop treating a ToolSearch prerequisite as neutral.

## Q4 — Target broad (z6) scope, stage hard requirements

The eventual (z6) target should include all three classes: failed-tool/repeated-Read telemetry from EF-059, reviewer-cost measurement from EF-067, and orchestrator-side substrate/read-discipline telemetry from EF-068. The common primitive is harness-side measurement.

But “included in target schema” and “hard precondition for every Tier 2.5 audit immediately” should be separated. D2.2 available-at-best-effort is the correct initial posture while the capture mechanism is proved. D2.1 always-available-always-read becomes appropriate only after the digest is generated by a mechanism that is not primarily agent-mediated.

## Q5 — Prefer CM1/CM2 for resolution; allow CM3 for transition; do not count CM4 as resolving laundering

For a true (z6) resolution, CM1 or CM2 is required because they most directly displace model self-report. CM3 can be a useful bridge if the transcript is harness-recorded and digest construction is reproducible. CM4, in-session structured emission, is not enough to resolve EF-059/067/068 because it leaves the relevant fact at agent emission time.

This mirrors `validation-approach.md` v7 §(z5): the ledger was revised to be “authoritative-not-witness” because a merely-read artefact becomes another record-not-engaged surface. A manually emitted telemetry digest has the same defect unless backed by harness records.

## Q6 — Direction C now, Direction B as the target; Direction A only if cost fields keep being treated as evidence

EF-067’s intake proves that `duration_minutes` and `reviewer_cost` are unreliable as evidence. It does not prove that the engine should erase the cost-observation pattern entirely. Direction A is clean but too destructive relative to WX-62-1’s closure pattern: it risks retroactively discarding the observation layer that surfaced §10.4-M25 audit-cost-budget pressure.

Direction C should land immediately: relabel reviewer cost fields as self-reported honest-limit material and prevent them from firing budget conclusions as if harness-measured. Direction B should be the phase-two target under (z6), replacing self-report with `reviewer_invocation_wall_clock_seconds` and token-count fields when the harness can supply them. If synthesis chooses Direction A, preserve a minority that A is operationally clean but too blunt.

## Q7 — Use 00-assessment plus close evidence now; move toward structured declaration

A close-narrative-only grep is too weak. Design-space §7 notes false-positive risk from substring checks in the check 27 over-fire chain. For a WARN-only check 29, the minimum should inspect both `00-assessment.md` and `03-close.md`: session-open substrate use belongs in the opening assessment, while close should record summary and honest limits.

The better target is structured declaration, but only if it does not become another self-report masquerading as measurement. A structured field such as substrate invocations is useful for validator ergonomics; it should be treated as evidence of declaration, not evidence of actual invocation until backed by harness telemetry.

## Q8 — Hybrid adoption

Adopt a bounded (β)-like change on the S058 same-session-bounded model if the synthesis has sufficient convergence: load-by-default, required `forward_references`, and WARN-only check 29 against 00-assessment plus close. Then run (γ) as a S062-style multi-session phase-3 arc after the capture locus is selected and one observation window can distinguish durable behavior change from design-space-salience compliance.

This is not indefinite deferral of EF-059. EF-059 triage says all activation preconditions are satisfied. The hybrid position is that activation warrants the arc, while evidence-floor discipline still requires not laundering the full implementation through a bundle that has not paid its implementation-specific costs.

## Q9 — Defer EF-068-read-write-rebalance unless operator explicitly reopens it

Do not open the four-record bundle at S071 by default. EF-068-substrate-load-bearing triage explicitly says the sibling read-write-rebalance record is not included and that S069 D-255 preserves separate-scope with operator-discretionary reopen. That default should hold absent operator surface or a demonstrated hard dependency.

Bundling the sibling now risks exactly the laundering pattern P4 is tasked to audit: a valid concern gets pulled into a larger arc because the language sounds related, not because the decision dependency is necessary.

## Q10 — Engine-v13 for bounded correction; later substantive bump for full digest

Candidate (β) is an engine-v13 candidate because it changes `prompts/development.md` and `tools/validate.sh`, but it is a bounded bump. Candidate (γ) is a substantive `validation-approach.md` v7 → v8 style revision with new (z6) digest semantics and reviewer-prompt-template implications. Under (ε), expect two bumps unless the first bounded correction is adopted without engine-definition change, which seems unlikely if `forward_references` becomes required.

The §10.4-M25 cadence concern does not block v13, but it argues against hiding a large digest implementation inside a “minor fix” narrative.

## Cross-product candidate position

I favor **(ε) Hybrid bounded-then-extended**, with **(β)** as the first-phase payload and **(γ)** as a committed but separately gated implementation arc.

The evidence audit is as follows. Design-space §3.1’s substrate non-use chain is valid evidence that optional substrate use is not durable under current prompts and deferred-tool loading. It validates load-by-default, required session-open `forward_references`, and a WARN-only evidence probe. It is narrower evidence for full (z6), because the chain measures non-use of a specific substrate habit, not the full feasibility or cost of harness telemetry.

Design-space §3.2’s reviewer self-report chain is valid evidence that reviewer wall-clock and token self-reports are unreliable. The closed-loop baseline is the structural problem. The n=3 chain is enough to stop treating those fields as measured evidence now. It is not enough to erase the cost-observation surface entirely, because EF-067’s own triage preserves three reasonable directions and WX-62-1 made reviewer-cost observation part of the mechanism’s learning.

EF-059 triage is decisive that (z6) is activated. It is not decisive that (z6) must be implemented in the largest form as the immediate next adoption. The right decision is: same-session-bounded adoption of (β)-class correction if convergence permits, plus a named multi-session (γ) arc with CM1/CM2 preference and D2.2 initial availability.

Family-rule check: S071 MAD execution satisfies the two-family perspective shape described in design-space §9: orchestrator/P1/P2 Claude-family and P3/P4 codex/OpenAI-family. For the S071 close Tier 2.5 audit, `validation-approach.md` v7 §Tier 2.5 reviewer-family rule still requires a reviewer distinct from the orchestrator family and not the close-author, primary implementer, or accountable doer. The close reviewer should not be a re-instance of P3 or P4 validating our own load-bearing claims; use a fresh non-overlapping invocation or another non-Anthropic family, with overlap disclosed if any.

## Frame critique (if any)

The design-space correctly identifies the shared primitive as harness-side measurement, but it slightly over-unifies the adoption decision. “Missing measurement” is not one problem. It appears here as at least three surfaces: enforcing a session-open habit, measuring reviewer cost, and detecting hidden tool/read patterns. Those surfaces can share a digest target without sharing the same rollout threshold.

Second, operator audit should not be framed only as evidence of engine failure. EF-067 and EF-068 both surfaced because Layer 6.2 worked. `validation-approach.md` v7 §Bootstrap-Paradox Layered Handling explicitly makes operator audit the outer counter-pressure. The right conclusion is not “operator audit failed to prevent laundering,” but “operator audit is currently carrying too much of the detection load.” That supports shifting load inward, while preserving Layer 6 as a live check during the transition.

Third, the (γ) bundle risks bundling-by-laundering. EF-068 Direction 1 (required substrate use), EF-067 Direction B (harness-measured reviewer cost), and EF-059 digest implementation each has independent merit. Bundling them can make the combined cost look inevitable because each part points at “harness measurement.” The synthesis should preserve separate disposition for each: first-phase substrate habit correction, immediate reviewer-cost caveat, and separately scoped digest implementation.

## Honest limits

This perspective reasons from the supplied briefs, design-space, intake records, triage records, and `validation-approach.md` v7. I did not inspect the underlying S063/S064/S067 audit files or `/tmp` logs, so the EF-067 factual chain is accepted through the intake and design-space rather than reverified independently.

As a codex/OpenAI-family P4, I share family with P3 and cannot serve as a clean close reviewer for claims this perspective makes load-bearing. My laundering-audit stance has its own laundering surface: calling something “laundering” can become rhetoric. The specific findings above are therefore limited to evidence-chain scope, bundling, Q6 disposition, and Q9 scope.

No external framework is intended as a load-bearing import. The “stage first, harden later” position is grounded in S058/S062 precedents as described in the shared brief and design-space, not an outside rollout doctrine.

## Dissent-preservation

If synthesis adopts immediate full **(γ)**, preserve this minority: the evidence validates harness-side movement, but the §3.1 and §3.2 chains validate narrower immediate corrections than the full bundled digest. Full (z6) may be right as a target, but adopting it as one bundle risks laundering implementation cost and capture-locus uncertainty through a shared-root-cause frame.

If synthesis adopts **(α)** only, preserve this minority: spec-only correction is too weak because EF-068’s central evidence is that encouragement without a mechanical probe decays to n→0. A WARN-only check 29 over both `00-assessment.md` and `03-close.md` is the minimum useful counter-pressure.

If synthesis adopts EF-067 Direction A, preserve this minority: dropping reviewer-cost fields closes the immediate evidence problem but discards WX-62-1’s cost-observation surface too aggressively. Direction C now plus Direction B later is the cleaner continuity-preserving path.

If synthesis opens the four-record bundle including EF-068-read-write-rebalance without operator signal, preserve this minority: S069 D-255’s separate-scope default should control unless a concrete dependency is shown.