"""issues export: regenerate open-issues/*.md from the issues substrate table."""

from __future__ import annotations

import sqlite3
from pathlib import Path

from .manifest import record_manifest_entry, workspace_relative


def _export_issues(conn: sqlite3.Connection, write: bool = False) -> dict:
    """Materialise open-issues/<alias>.md from the issues substrate table.

    One file per issue. Open issues land in `open-issues/`; resolved/superseded
    in `open-issues/resolved/`. Frontmatter mirrors the pre-S088 markdown shape
    so callers (and humans browsing git) see a familiar surface; body is the
    body atom if present, else the summary atom, else empty.
    """
    rows = conn.execute(
        "SELECT i.issue_id, i.alias, i.priority, i.status, "
        "       i.surfaced_session_id, i.resolved_session_id, i.resolved_at, "
        "       ta_t.text AS title, ta_s.text AS summary, ta_b.text AS body, "
        "       sf.workspace_session_no AS surfaced_wno, "
        "       sr.workspace_session_no AS resolved_wno "
        "FROM issues i "
        "JOIN text_atoms ta_t ON ta_t.atom_id=i.title_atom_id "
        "LEFT JOIN text_atoms ta_s ON ta_s.atom_id=i.summary_atom_id "
        "LEFT JOIN text_atoms ta_b ON ta_b.atom_id=i.body_atom_id "
        "JOIN sessions sf ON sf.session_id=i.surfaced_session_id "
        "LEFT JOIN sessions sr ON sr.session_id=i.resolved_session_id "
        "ORDER BY i.alias"
    ).fetchall()

    files: dict[str, str] = {}
    for r in rows:
        is_terminal = r["status"] in ("resolved", "superseded")
        rel = "resolved" if is_terminal else ""
        path = (
            Path("open-issues") / rel / f"{r['alias']}.md"
            if rel
            else Path("open-issues") / f"{r['alias']}.md"
        )
        lines = [
            "---",
            f"id: {r['alias']}",
            f"status: {r['status']}",
            f"priority: {r['priority']}",
            f"surfaced-in-session: {r['surfaced_wno'] or ''}",
        ]
        if r["resolved_wno"]:
            lines.append(f"resolved-in-session: {r['resolved_wno']}")
        if r["resolved_at"]:
            lines.append(f"resolved-at: {r['resolved_at']}")
        lines.append("generated_by: selvedge export --issues")
        lines.append("---")
        lines.append("")
        lines.append(f"# {r['title']}")
        lines.append("")
        if r["summary"]:
            lines.append(r["summary"])
            lines.append("")
        if r["body"]:
            lines.append(r["body"])
            lines.append("")
        # Footer flagging substrate compression. Bodies authored by the S088
        # backfill subagent are compressed canonical summaries (4000-char cap);
        # bodies of issues created post-engine-v22 reflect the author's intent
        # at submit time.
        lines.append("---")
        lines.append(
            "*Substrate-canonical: regenerated from `issues` row by `selvedge export --issues`. "
            "Body atoms are capped at 4000 chars; if this issue predates engine-v22 (pre-S088) the body "
            "is a compressed canonical summary and the verbatim pre-substrate prose is in git history.*"
        )
        files[str(path)] = "\n".join(lines).rstrip() + "\n"

    idx_lines = [
        "# Open issues — substrate-canonical (regenerated by `selvedge export --issues`)",
        "",
        "Issues live in the `issues` substrate table. The files below are a",
        "deterministic export from substrate rows; do not hand-edit. Use",
        "`bin/selvedge submit issue` and `submit issue-disposition` to mutate.",
        "",
    ]
    open_rows = [r for r in rows if r["status"] not in ("resolved", "superseded")]
    closed_rows = [r for r in rows if r["status"] in ("resolved", "superseded")]
    if open_rows:
        idx_lines.append("## Open")
        idx_lines.append("")
        idx_lines.append("| Alias | Priority | Status | Title |")
        idx_lines.append("|-------|----------|--------|-------|")
        for r in open_rows:
            idx_lines.append(
                f"| [{r['alias']}]({r['alias']}.md) | {r['priority']} | {r['status']} | {r['title']} |"
            )
        idx_lines.append("")
    if closed_rows:
        idx_lines.append("## Resolved")
        idx_lines.append("")
        idx_lines.append("| Alias | Resolved-in | Title |")
        idx_lines.append("|-------|-------------|-------|")
        for r in closed_rows:
            idx_lines.append(
                f"| [{r['alias']}](resolved/{r['alias']}.md) | S{r['resolved_wno']:03d} | {r['title']} |"
            )
        idx_lines.append("")
    files["open-issues/index.md"] = "\n".join(idx_lines).rstrip() + "\n"

    # Compute reconciliation: files currently on disk under open-issues/ that
    # are not in the substrate's target set must be deleted (or, in dry-run,
    # reported as `files_to_delete`). Without this, an open->resolved
    # transition leaves the stale top-level path next to the new resolved/
    # path — flagged in EF-S092-2.
    target_paths = {Path(pp).resolve() for pp in files.keys()}
    on_disk: list[Path] = []
    oi = Path("open-issues")
    if oi.exists():
        on_disk.extend(p for p in oi.glob("*.md"))
        resolved_dir = oi / "resolved"
        if resolved_dir.exists():
            on_disk.extend(p for p in resolved_dir.glob("*.md"))
    stale = sorted(str(p) for p in on_disk if p.resolve() not in target_paths)

    if write:
        for path_str, content in files.items():
            p = Path(path_str)
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content)
            kind = "open_issues_index" if p.name == "index.md" else "open_issue"
            record_manifest_entry(
                conn,
                kind=kind,
                path=p,
                session_no=None,
                content=content,
            )
        for s in stale:
            stale_path = Path(s)
            # DELETE manifest row BEFORE unlink so DELETE failure leaves
            # both intact (recoverable) rather than orphan-row + missing-file.
            try:
                rel = workspace_relative(stale_path)
                conn.execute("DELETE FROM export_manifest WHERE path=?", (rel,))
                conn.commit()
            except (sqlite3.Error, ValueError):
                pass
            stale_path.unlink()
        return {
            "dry_run": False,
            "issues_exported": len(rows),
            "files_written": sorted(files.keys()),
            "files_deleted": stale,
        }
    return {
        "dry_run": True,
        "issues_exported": len(rows),
        "files_planned": sorted(files.keys()),
        "files_to_delete": stale,
    }
