"""Workspace-wide `spec_versions` index export (OI-S081-6 / DV-S081-1).

Writes `specifications/_versions.md`: a deterministic table listing every
`spec_versions` row with body path, body sha256, status, and the session
that authored it. Bodies themselves live at their `body_path` already and
are committed alongside this index; the table is the version-and-supersession
ledger that substrate-loss would otherwise make tacit.

Regenerated each close from `bin/selvedge export --session N --write` so
the close-ceremony command emits the index in the same shot as the per-
session provenance dir.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

INDEX_PATH = Path("specifications/_versions.md")


def _export_spec_versions(conn: sqlite3.Connection, write: bool = False) -> dict:
    rows = conn.execute(
        "SELECT sv.spec_version_id, sv.spec_id, sv.version, sv.status, "
        "       sv.body_path, sv.body_sha256, sv.body_canonical_in_substrate, "
        "       s.workspace_session_no AS wno "
        "FROM spec_versions sv "
        "JOIN sessions s ON s.session_id=sv.session_id "
        "ORDER BY sv.spec_id, sv.version"
    ).fetchall()

    lines = [
        "# Spec versions — substrate-canonical (regenerated by `selvedge export --session N --write`)",
        "",
        "Every `spec_versions` row in the substrate. Bodies live at the listed",
        "`body_path`; this index is the version + supersession ledger so a",
        "substrate wipe leaves the chain recoverable from markdown alone.",
        "",
        "| Spec | Version | Status | Body path | Body sha256 | Canonical-in-substrate | Created in |",
        "|------|---------|--------|-----------|-------------|------------------------|------------|",
    ]
    for r in rows:
        canonical = "yes" if r["body_canonical_in_substrate"] else "no"
        wno = f"S{r['wno']:03d}" if r["wno"] is not None else "(unknown)"
        lines.append(
            f"| {r['spec_id']} | {r['version']} | {r['status']} | "
            f"`{r['body_path']}` | `{r['body_sha256'][:16]}…` | {canonical} | {wno} |"
        )
    lines.append("")
    body = "\n".join(lines)

    if write:
        INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
        INDEX_PATH.write_text(body)
        return {
            "dry_run": False,
            "spec_versions_exported": len(rows),
            "file_written": str(INDEX_PATH),
        }
    return {
        "dry_run": True,
        "spec_versions_exported": len(rows),
        "file_planned": str(INDEX_PATH),
    }
